gfch100: disable pager (more) in cpss
Change-Id: I5a457d9b8f5819284fc725205e99bd0709d184b7

diff --git a/fs/skeleton/usr/bin/cpss_wrapper b/fs/skeleton/usr/bin/cpss_wrapper
--- a/fs/skeleton/usr/bin/cpss_wrapper
+++ b/fs/skeleton/usr/bin/cpss_wrapper
@@ -101,6 +101,13 @@ if experiment CpssNoInit; then
   echo "$0: experiment CpssNoInit enabled, skipping init and 2011 config." >&2
 else
 
+  # disable pager
+  cpss_cmd <<EOF || die "failed to disable pager"
+    debug
+      set print pause disable
+    end
+EOF
+
   # init the switch, check for result
   cpss_cmd <<EOF | grep "Init system returned:0" || die "cpssInitSystem failed"
     cpssInitSystem 19,2,0
