ath10k-reset: more robustness.
UMH_NO_WAIT seems to not actually run the requested program sometimes; based
on a separate test I wrote, this is not actually related to running it in
interrupt/atomic context.  It just sometimes doesn't work and doesn't report
any reason why not.  Rather than trying to debug that right now, switch to
using UMH_WAIT_EXEC instead, which seems to work reliably, but doesn't work
in atomic contexts.  So when the firmware crashes, arrange for the script to
get launched from the ath10k tasklet instead, which can safely use
UMH_WAIT_EXEC.

While we're here, improve ath10k-reset to work even if some of the modules
have previously been removed.

Also, there was a bug in the debugfs handling of simulate_fw_crash, where it
would report the wrong number of bytes being written.  This would sometimes
cause the driver to try to double-reset when simulating a crash, and
hilarity would ensue.

Change-Id: I51de304fb060a8ccd234d5295aa4e9f1f32c39f8

diff --git a/fs/skeleton/bin/ath10k-reset b/fs/skeleton/bin/ath10k-reset
--- a/fs/skeleton/bin/ath10k-reset
+++ b/fs/skeleton/bin/ath10k-reset
@@ -31,7 +31,12 @@ export PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
 {
   echo "removing drivers..." >&2
   pkill -9 hostapd
-  rmmod ath10k_pci ath9k &&
+  for m in ath10k_pci ath9k; do
+    while [ -e "/sys/module/$m" ]; do
+      echo "removing module '$m'..." >&2
+      rmmod "$m" || { echo "failed to remove '$m'" >&2; exit 1; }
+    done
+  done
   echo "resetting PCIe buses..." >&2 &&
   echo 1 >/sys/devices/platform/pcie.0/device_reset &&
   echo 1 >/sys/devices/platform/pcie.1/device_reset &&
