Enable dbus announcement when tlsdate updates time
If dbus package is enabled:
  1. Enable dbus support.
  2. Install tlsdate dbus conf.

Run tlsdate-dbus-announce in run-tlsdate.

Change-Id: I07d50e87b8e3bc2bb15e861a97ad712fa2fcc42a

diff --git a/fs/skeleton/bin/run-tlsdate b/fs/skeleton/bin/run-tlsdate
--- a/fs/skeleton/bin/run-tlsdate
+++ b/fs/skeleton/bin/run-tlsdate
@@ -137,6 +137,14 @@ while :; do
 done
 
 
+# Now let dbus services know that time is sane.
+tlsdate-dbus-announce
+# Status code 1 means error and 2 means no dbus support.
+if [ $? == 1 ]; then
+  echo "tlsdate-dbus-announce failed." >&2
+fi
+
+
 # Now the clock is as close as it can get with one-off syncs.  We have
 # to start fine tuning the clock rate.
 mkdir -p /tmp/clockspeed/etc
