Add support for installing lionhead I2C sysfs entries.
- Take I2C switches out of reset.
- Load kernel modules for lionhead I2C devices
- Create sysfs entries for lionhead I2C devices
- Don't fail setting up a gpio entry if an attribute doesn't exist.
  For instance I2C gpios don't have an "edge" attribute.
- Add hw_ver entry to /etc/platforms for general use.

Change-Id: I6856e6fa7e70b7e4ea2cda9a1f9322c31b7509ca

diff --git a/fs/skeleton/bin/update-gpio-links b/fs/skeleton/bin/update-gpio-links
--- a/fs/skeleton/bin/update-gpio-links
+++ b/fs/skeleton/bin/update-gpio-links
@@ -60,14 +60,14 @@ set_gpio_prop()
   gdir=$(gpio_dir "$gpio")
   keyfile="$gdir/$key"
 
-  if [ ! -f "$keyfile" ]; then
-    echo "set_gpio_prop: '$keyfile' not found" >&2
-    return 1
-  fi
-
   # allow "" and "-" as noop values
   if [ -z "$value" ] || [ "$value" = "-" ]; then
     return 0
+  fi
+
+  if [ ! -f "$keyfile" ]; then
+    echo "set_gpio_prop: '$keyfile' not found" >&2
+    return 1
   fi
 
   echo "$value" >"$keyfile" || return 1
