update-gpio-links: fix bug that didn't set props
	* also add check for prop file existence to catch
	  similar bugs in future

Change-Id: I834e451dc4287af9cd5b9ad19d67fab89629bd60

diff --git a/fs/skeleton/bin/update-gpio-links b/fs/skeleton/bin/update-gpio-links
--- a/fs/skeleton/bin/update-gpio-links
+++ b/fs/skeleton/bin/update-gpio-links
@@ -55,16 +55,22 @@ reexport_gpio()
 set_gpio_prop()
 {
   local gpio="$1" key="$2" value="$3"
-  local gdir
+  local gdir keyfile
 
   gdir=$(gpio_dir "$gpio")
+  keyfile="$gdir/$key"
+
+  if [ ! -f "$keyfile" ]; then
+    echo "set_gpio_prop: '$keyfile' not found" >&2
+    return 1
+  fi
 
   # allow "" and "-" as noop values
   if [ -z "$value" ] || [ "$value" = "-" ]; then
     return 0
   fi
 
-  echo "$value" >"$gdir/$key" || return 1
+  echo "$value" >"$keyfile" || return 1
 
   return 0
 }
@@ -119,9 +125,9 @@ create_gpio_links()
     fi
 
     # set properties (may be noops)
-    if ! set_gpio_prop active_low "$active_low" ||
-       ! set_gpio_prop edge "$edge" ||
-       ! set_gpio_prop direction "$direction"; then
+    if ! set_gpio_prop "$gpio" active_low "$active_low" ||
+       ! set_gpio_prop "$gpio" edge "$edge" ||
+       ! set_gpio_prop "$gpio" direction "$direction"; then
       err=1
       continue
     fi
