Print ath10k cal_data hash on boot.
We want to compare values across the fleet to analyze differences.

Change-Id: If38c1a5a6937a53077074258f989a07c037b46b8

diff --git a/fs/skeleton/sbin/hotplug b/fs/skeleton/sbin/hotplug
--- a/fs/skeleton/sbin/hotplug
+++ b/fs/skeleton/sbin/hotplug
@@ -40,6 +40,26 @@ load_firmware() {
   echo "  ...loaded firmware '$1'"
 }
 
+print_ath10k_cal_hash() {
+  local checks=0
+  local ath10k_cal=/sys/kernel/debug/ieee80211/phy1/ath10k/cal_data
+  local ath10k_cal_tmp=/tmp/ath10k_cal_data
+  while :; do
+    cat "$ath10k_cal" >"$ath10k_cal_tmp" 2>/dev/null
+    if [ -s "$ath10k_cal_tmp" ]; then
+      break
+    fi
+    checks=$((checks + 1))
+    if [ "$checks" -gt 100 ]; then
+       echo "Unable to fetch ath10k calibration data" >&2
+       return
+    fi
+    sleep 0.1
+  done
+  # Print ath10k cal_data sha1 to logs.
+  echo "ath10k cal_data sha1sum: $(sha1sum $ath10k_cal_tmp | cut -d " " -f1)"
+  rm -f "$ath10k_cal_tmp"
+}
 
 case "$SUBSYSTEM-$ACTION" in
   input-add)
@@ -77,8 +97,14 @@ case "$SUBSYSTEM-$ACTION" in
     # At boot or device reset, a net add event is delivered for the primary
     # interface. Use this event to create a client interface, which is
     # created in user space unlike the primary interface.
-    if startswith "$INTERFACE" "wlan" && is-wireless-client; then
-      create_client_interface "$INTERFACE"
+    if startswith "$INTERFACE" "wlan"; then
+      if is-wireless-client; then
+        create_client_interface "$INTERFACE"
+      fi
+      if contains "GFRG200 GFRG210" "$(cat /etc/platform)" &&
+        [ "$INTERFACE" = "wlan1" ]; then
+        print_ath10k_cal_hash &
+      fi
     fi
     ;;
 esac
