simpleramfs/mounts: allow skipping dmverity on bruno B0 devices.
Since B0 doesn't have the fancy CFE bootloader, the fancy CFE bootloader
can't boot images with our fancy header.  Without the fancy header, we can't
initialize fancy dmverity. But it's okay, because B0 devices don't have any
interesting key information to protect anyway.

Change-Id: Idcdd74b188cca589b83ac54d4c327ee157c0cacc

diff --git a/fs/simpleramfs/mounts b/fs/simpleramfs/mounts
--- a/fs/simpleramfs/mounts
+++ b/fs/simpleramfs/mounts
@@ -128,9 +128,21 @@ elif [ -n "$ROOTDEV" ]; then
   args=$(readverity ${KERNELDEV})
   args=$(replacefirst "${args}" ROOT_DEV "${ROOTDEV}")
   args=$(replacefirst "${args}" HASH_DEV "${KERNELDEV}")
-  dmsetup create -r vroot --table "${args}" || die "dmsetup failed"
-  mount -o ro -t "$ROOTFSTYPE" /dev/mapper/vroot /rootfs || die "root='$ROOTDEV' mount failed"
-  log "Mounted root='$ROOTDEV'"
+  if ! dmsetup create -r vroot --table "${args}"; then
+    read x y z platform junk </proc/cpuinfo
+    if [ "$platform" = "BCM7425B0" ]; then
+      log 'dmsetup failed: platform is old B0 device, continuing anyway.'
+      mount -o ro -t "$ROOTFSTYPE" "$ROOTDEV" /rootfs ||
+          die "root='$ROOTDEV' mount failed"
+      log "Mounted root='$ROOTDEV'"
+    else
+      die "dmsetup failed"
+    fi
+  else
+    mount -o ro -t "$ROOTFSTYPE" /dev/mapper/vroot /rootfs ||
+        die "root='$ROOTDEV' mount failed (verity)"
+    log "Mounted root='$ROOTDEV' (verity)"
+  fi
 else
   die "No root= or nfsroot= provided."
 fi
