S50dropbear: try to persist the server cert.
S50dropbear auto-generates a certificate if the server doesn't already have
one, but it would always dump it in /tmp/dropbear, which means we got a
different certificate on every boot.  Not only did this add a couple of
seconds to the boot process, it also means you have to remove the server's
cert from your ~/.ssh/known_hosts all the time.

Instead, if /config is mounted read-write, save the certs there.  We still
fall back to /tmp just in case /config isn't available, since if that
happens, you might *really* wish there was an sshd to use to debug why.

Change-Id: I24387d3b15e6dcd9629578742eace7940af20bd6

diff --git a/package/dropbear/S50dropbear b/package/dropbear/S50dropbear
--- a/package/dropbear/S50dropbear
+++ b/package/dropbear/S50dropbear
@@ -6,27 +6,31 @@
 # Make sure this load is used for test
 [ -f /tmp/DEBUG ] || exit 0
 
-# Make sure the dropbearkey progam exists
-[ -f /usr/bin/dropbearkey ] || exit 0
-
 start() {
- 	echo -n "Starting dropbear sshd: "
-	# Make sure dropbear directory exists
-	if [ ! -d /etc/dropbear ] ; then
-		mkdir -p /etc/dropbear
-	fi
-	# Check for the Dropbear RSA key
-	if [ ! -f /etc/dropbear/dropbear_rsa_host_key ] ; then
-		echo -n "generating rsa key... "
-		/usr/bin/dropbearkey -t rsa -f /etc/dropbear/dropbear_rsa_host_key > /dev/null 2>&1
+	# Make sure dropbear directory exists.
+	#  /etc/dropbear links to /tmp/dropbear, which we can write to.
+	if mkdir -p /config/dropbear; then
+		ln -sf /config/dropbear /tmp
+	else
+		mkdir -p /tmp/dropbear
 	fi
 
-	# Check for the Dropbear DSS key
-	if [ ! -f /etc/dropbear/dropbear_dss_host_key ] ; then
-		echo -n "generating dsa key... "
-		/usr/bin/dropbearkey -t dss -f /etc/dropbear/dropbear_dss_host_key > /dev/null 2>&1
-	fi
+	# Check for the dropbear keys
 	umask 077
+	K1=/etc/dropbear/dropbear_rsa_host_key
+	K2=/etc/dropbear/dropbear_dss_host_key
+	if ! dropbearkey -y -f $K1 >/dev/null 2>&1; then
+		[ -e "$K1" ] && echo "BUG: $K1 existed, but invalid!"
+		rm -f $K1
+		dropbearkey -t rsa -f $K1
+	fi
+	if ! dropbearkey -y -f $K2 >/dev/null 2>&1; then
+		[ -e "$K2" ] && echo "BUG: $K2 existed, but invalid!"
+		rm -f $K2
+		dropbearkey -t dss -f $K2
+	fi
+
+	echo -n "Starting dropbear sshd: "
 	start-stop-daemon -S -q -p /var/run/dropbear.pid --exec /usr/sbin/dropbear
 	echo "OK"
 }
@@ -56,4 +60,3 @@ case "$1" in
 esac
 
 exit $?
-
