Add a 'make depcheck' target and fix missing Config.in dependencies.
We had a bunch of correctly-declared dependencies in *.mk, but we weren't
also setting them in Config.in, which resulted in some BR2_PACKAGE_*
variables not being set, which could lead to problems.  The main problem I
observed was that 'make source' would not actually download/extract all the
source for all the packages we used, because it only uses dependency
information from *.mk.  So we'd sometimes end up trying to download packages
at build time instead of during the initial sanity check.

This was particularly annoying because it cluttered the 'finaltargets'
section of the make output, with lines that rarely failed but often
obfuscated the real cause of a build failure when it happened.

Change-Id: I7cd96208a9c947eed2d11e9b7d6922077515d2e5

diff --git a/package/Makefile.package.in b/package/Makefile.package.in
--- a/package/Makefile.package.in
+++ b/package/Makefile.package.in
@@ -780,6 +780,22 @@ endif
 $(1)-show-depends: $(patsubst %,%-show-depends,$($(2)_DEPENDENCIES))
 			@echo $(1) : $$($(2)_DEPENDENCIES)
 
+$(1)-is-enabled:
+	@echo "is-enabled: $(1): '$$(BR2_PACKAGE_$(2))'"
+	$(Q) \
+	[ "$(1)" = linux ] || \
+	[ "$(1)" = automake ] || \
+	[ "$(1)" = autoconf ] || \
+	[ "$(1)" = libtool ] || \
+	[ "$(1)" = cmake ] || \
+	[ "$(1)" = gdb_target ] || \
+	if [ "$$(BR2_PACKAGE_$(2))" != 'y' ]; then \
+		echo "error: $(1) is depended on but BR2_PACKAGE_$(2) not set" >&2; \
+		exit 1; \
+	fi
+
+$(1)-depcheck:		$$(filter-out host-%,$$(patsubst %,%-is-enabled,$$($(2)_DEPENDENCIES)))
+
 $(1)-uninstall:		$(1)-configure $$($(2)_TARGET_UNINSTALL)
 
 $(1)-clean:		$(1)-uninstall \
